# Table in db
TABLE_NAME = "ExamDB"

# Primary key collection
USER_COLLECTION_NAME = "USER"
TEST_COLLECTION_NAME = "TEST"
QUESTION_COLLECTION_NAME = "QUESTION"
ANSWER_COLLECTION_NAME = "ANSWER"
TYPE_COLLECTION_NAME = "TYPE"
